version: '3'

services:
  db:
    image: postgres:latest
    container_name: pilacoin-db
    environment:
      POSTGRES_DB: pilacoin
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
