spring:
  data:
    mongodb:
      authentication-database: admin
      repositories.enabled: true
      database: pilacoin
      host: localhost
      port: 27017
      username: user
      password: pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.NoopDialect

  rabbitmq:
    host: srv-ceesp.proj.ufsm.br
    port: 8082
    username: guest
    password: guest

queue:
  dificuldade: dificuldade
  pila-minerado: pila-minerado
  pila-validado: pila-validado
  descobre-bloco: descobre-bloco
  bloco-minerado: bloco-minerado
  bloco-validado: bloco-validado
  transferir-pila: transferir-pila


pilacoin:
  username: carara-schmitzhaus

keypair:
  algorithm: RSA
  size: 1024
  privateKeyPath: private_key.pem
  publicKeyPath: public_key.pem



